services:
  backend:
    build:
      context: ./Backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  frontend:
      build:
        context: ./Frontend
      ports:
        - "8080:80"  # Nginx expose le port 80
      depends_on:
        - backend
      environment:
        - NODE_ENV=production