# Étape 1 : Utiliser une image Node officielle
FROM node:20

# Étape 2 : Définir le dossier de travail dans le conteneur
WORKDIR /app

# Étape 3 : Copier les fichiers de dépendances
COPY package*.json ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le reste de ton code
COPY . .

# Étape 6 : Exposer le port sur lequel ton app écoute
EXPOSE 3000

# Étape 7 : Démarrer l'application
CMD ["node", "server.js"]
